apiVersion: 1
datasources:
  - name: Mimir
    type: prometheus
    uid: mimir-ds
    access: proxy
    url: http://mimir:9009
    isDefault: true
    version: 1
    editable: true
  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
  - name: Tempo
    type: tempo
    uid: tempo-ds
    access: proxy
    url: http://tempo:3200
    version: 1
    editable: true
    # Thiết lập liên kết với Loki (Trace to Logs)
    jsonData:
      lokiSearch:
        datasourceUid: loki-ds